// packages/react/src/blocks/BadgeGroupBlock.tsx
import type { BadgeGroupData } from '@mcp-interactive-ui/types';

export interface BadgeGroupBlockProps {
  data: BadgeGroupData;
  className?: string;
}

export function BadgeGroupBlock({ data, className }: BadgeGroupBlockProps): JSX.Element {
  const layoutClass = {
    horizontal: 'flex flex-row gap-2',
    vertical: 'flex flex-col gap-2',
    wrap: 'flex flex-wrap gap-2',
  }[data.layout || 'wrap'];

  const sizeClass = {
    sm: 'text-xs px-2 py-1',
    md: 'text-sm px-2.5 py-1.5',
    lg: 'text-base px-3 py-2',
  }[data.size || 'md'];

  const variantClass = (variant: string) => {
    switch (variant) {
      case 'destructive':
        return 'bg-destructive text-destructive-foreground';
      case 'outline':
        return 'border border-input bg-background';
      case 'success':
        return 'bg-green-500 text-white';
      case 'warning':
        return 'bg-yellow-500 text-white';
      default:
        return 'bg-secondary text-secondary-foreground';
    }
  };

  return (
    <div className={className ?? 'rounded-lg border bg-card text-card-foreground shadow-sm'}>
      {data.title && (
        <div className="p-6 pb-4">
          <h3 className="text-lg font-semibold">{data.title}</h3>
        </div>
      )}

      <div className={data.title ? 'px-6 pb-6' : 'p-6'}>
        <div className={layoutClass}>
          {data.badges.map((badge) => (
            <span
              key={badge.id}
              className={`inline-flex items-center rounded-full font-medium ${sizeClass} ${variantClass(
                badge.variant || 'default'
              )}`}
            >
              {badge.icon && <span className="mr-1">{badge.icon}</span>}
              {badge.label}
              {badge.removable && (
                <button className="ml-1 hover:opacity-70">✕</button>
              )}
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}

// packages/vue/src/components/blocks/BadgeGroupBlock.vue
<template>
  <div class="rounded-lg border bg-card text-card-foreground shadow-sm p-6">
    <h3 v-if="data.title" class="text-lg font-semibold mb-4">{{ data.title }}</h3>

    <div class="flex flex-wrap gap-2">
      <span
        v-for="(badge, index) in data.badges"
        :key="index"
        :class="[
          'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium transition-colors',
          variantClasses[badge.variant ?? 'default'],
          sizeClasses[data.size ?? 'md'],
          badge.onClick ? 'cursor-pointer hover:opacity-80' : ''
        ]"
        @click="handleClick(badge, index)"
      >
        <span v-if="badge.icon" class="mr-1">{{ badge.icon }}</span>
        {{ badge.label }}
        <button
          v-if="badge.removable"
          type="button"
          @click.stop="removeBadge(index)"
          class="ml-1 -mr-1 h-3 w-3 rounded-full inline-flex items-center justify-center hover:bg-black/10 dark:hover:bg-white/10"
        >
          <svg class="h-3 w-3" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </span>
    </div>

    <p v-if="data.description" class="mt-4 text-sm text-muted-foreground">{{ data.description }}</p>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import type { BadgeGroupData } from '@mcp-interactive-ui/types';

interface Props {
  data: BadgeGroupData;
  blockId?: string;
}

const props = defineProps<Props>();
const emit = defineEmits<{
  action: [action: string, payload: unknown];
}>();

const badges = ref([...props.data.badges]);

const variantClasses: Record<string, string> = {
  default: 'bg-primary text-primary-foreground',
  secondary: 'bg-secondary text-secondary-foreground',
  success: 'bg-green-500/10 text-green-700 dark:text-green-300',
  warning: 'bg-yellow-500/10 text-yellow-700 dark:text-yellow-300',
  error: 'bg-destructive/10 text-destructive',
  outline: 'border border-input bg-background text-foreground',
};

const sizeClasses: Record<string, string> = {
  sm: 'text-xs px-2 py-0.5',
  md: 'text-xs px-2.5 py-0.5',
  lg: 'text-sm px-3 py-1',
};

const handleClick = (badge: typeof badges.value[0], index: number) => {
  if (badge.onClick) {
    emit('action', 'badge_click', {
      index,
      label: badge.label,
      value: badge.value,
    });
  }
};

const removeBadge = (index: number) => {
  const removed = badges.value[index];
  badges.value.splice(index, 1);
  emit('action', 'badge_remove', {
    index,
    label: removed.label,
    value: removed.value,
  });
};
</script>
