// packages/react/src/blocks/CodeBlock.tsx
import { useState, useCallback } from 'react';
import type { CodeData } from '@mcp-interactive-ui/types';

export interface CodeBlockProps {
  data: CodeData;
  className?: string;
}

/**
 * Renders a `code` block with syntax highlighting and copy functionality.
 */
export function CodeBlock({ data, className }: CodeBlockProps): JSX.Element {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(data.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [data.content]);

  const lines = data.content.split('\n');
  const startLine = 1;
  const maxLineNumberWidth = String(lines.length).length;

  return (
    <div className={className ?? 'rounded-lg border bg-card text-card-foreground shadow-sm overflow-hidden'}>
      {/* Header */}
      {(data.filename || data.copyable) && (
        <div className="flex items-center justify-between px-4 py-2 bg-muted border-b">
          {data.filename && (
            <span className="text-sm font-mono text-muted-foreground">{data.filename}</span>
          )}
          {data.copyable && (
            <button
              onClick={handleCopy}
              className="ml-auto inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-8 px-3 py-1"
            >
              {copied ? 'Copied!' : 'Copy'}
            </button>
          )}
        </div>
      )}

      {/* Code */}
      <div className="overflow-x-auto bg-background">
        <pre className="p-4 text-sm font-mono text-foreground">
          {lines.map((line, idx) => {
            const lineNumber = startLine + idx;
            const isHighlighted = data.highlightLines?.includes(lineNumber);

            return (
              <div
                key={idx}
                className={`${
                  isHighlighted ? 'bg-yellow-500/10' : ''
                } ${data.showLineNumbers ? 'flex' : ''}`}
              >
                {data.showLineNumbers && (
                  <span
                    className="inline-block w-12 pr-4 text-right text-muted-foreground select-none"
                    style={{ minWidth: `${maxLineNumberWidth * 0.6 + 2}rem` }}
                  >
                    {lineNumber}
                  </span>
                )}
                <span className={data.wrapLines ? 'break-words' : 'whitespace-pre'}>
                  {line}
                </span>
              </div>
            );
          })}
        </pre>
      </div>
    </div>
  );
}

// packages/vue/src/components/blocks/CodeBlock.vue
<template>
  <div class="rounded-lg border bg-card text-card-foreground shadow-sm overflow-hidden">
    <!-- Header with filename and copy button -->
    <div
      v-if="data.filename || data.copyable !== false"
      class="flex items-center justify-between px-4 py-3 border-b bg-muted/50"
    >
      <div class="flex items-center gap-2">
        <span v-if="data.language" class="text-xs font-medium px-2 py-1 rounded bg-muted text-muted-foreground uppercase">
          {{ data.language }}
        </span>
        <span v-if="data.filename" class="text-sm font-medium text-foreground">{{ data.filename }}</span>
      </div>
      <button
        v-if="data.copyable !== false"
        type="button"
        @click="copyToClipboard"
        class="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors"
      >
        <svg
          v-if="!copied"
          class="h-4 w-4"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
        </svg>
        <svg
          v-else
          class="h-4 w-4 text-green-500"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
        </svg>
        {{ copied ? 'Copied!' : 'Copy' }}
      </button>
    </div>

    <!-- Code content -->
    <div class="relative">
      <pre
        :class="[
          'p-4 text-sm font-mono overflow-x-auto bg-muted/30',
          data.wrapLines ? 'whitespace-pre-wrap break-all' : 'whitespace-pre'
        ]"
        :style="maxHeightStyle"
      ><code><span
          v-for="(line, index) in lines"
          :key="index"
          class="block"
          :class="[
            showLineNumbers ? 'pl-12' : '',
            isHighlighted(index + 1) ? 'bg-yellow-500/10 -mx-4 px-4' : ''
          ]"
        ><span
            v-if="showLineNumbers"
            class="absolute left-0 w-8 text-right text-muted-foreground select-none"
          >{{ index + 1 }}</span><span class="text-foreground">{{ line || ' ' }}</span></span></code></pre>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import type { CodeData } from '@mcp-interactive-ui/types';

interface Props {
  data: CodeData;
  blockId?: string;
}

const props = defineProps<Props>();

const copied = ref(false);

const showLineNumbers = computed(() => props.data.showLineNumbers ?? true);

const lines = computed(() => {
  return props.data.content.split('\n');
});

const maxHeightStyle = computed(() => {
  if (props.data.maxHeight) {
    return { maxHeight: `${props.data.maxHeight}px`, overflowY: 'auto' };
  }
  return {};
});

const isHighlighted = (lineNumber: number) => {
  return props.data.highlightLines?.includes(lineNumber) ?? false;
};

const copyToClipboard = async () => {
  try {
    await navigator.clipboard.writeText(props.data.content);
    copied.value = true;
    setTimeout(() => {
      copied.value = false;
    }, 2000);
  } catch (err) {
    console.error('Failed to copy:', err);
  }
};
</script>
