// packages/react/src/blocks/NoticeBlock.tsx
import type { NoticeData, NoticeVariant } from '@mcp-interactive-ui/types';

export interface NoticeBlockProps {
  data: NoticeData;
  className?: string;
}

const VARIANT_CLASSES: Record<NoticeVariant, string> = {
  info: 'border-sky-200 bg-sky-50 text-sky-900 dark:border-sky-900/60 dark:bg-sky-950/40 dark:text-sky-100',
  success:
    'border-emerald-200 bg-emerald-50 text-emerald-900 dark:border-emerald-900/60 dark:bg-emerald-950/40 dark:text-emerald-100',
  warning:
    'border-amber-200 bg-amber-50 text-amber-900 dark:border-amber-900/60 dark:bg-amber-950/40 dark:text-amber-100',
  error:
    'border-rose-200 bg-rose-50 text-rose-900 dark:border-rose-900/60 dark:bg-rose-950/40 dark:text-rose-100',
};

export function NoticeBlock({ data, className }: NoticeBlockProps): JSX.Element {
  return (
    <div
      role="alert"
      data-variant={data.variant}
      className={
        className ??
        `relative w-full rounded-lg border p-4 text-sm ${VARIANT_CLASSES[data.variant]}`
      }
    >
      {data.title ? <div className="mb-1 font-medium leading-none">{data.title}</div> : null}
      <div className="leading-relaxed">{data.message}</div>
    </div>
  );
}

// packages/vue/src/components/blocks/NoticeBlock.vue
<template>
  <div
    class="rounded-lg border p-4"
    :class="variantClasses[data.variant || 'default']"
  >
    <div class="flex items-start gap-4">
      <span v-if="data.icon" class="text-lg shrink-0">{{ data.icon }}</span>
      <div class="flex-1">
        <h4 v-if="data.title" class="font-semibold mb-1">{{ data.title }}</h4>
        <p class="text-sm">{{ data.message }}</p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { NoticeData } from '@mcp-interactive-ui/types';

interface Props {
  data: NoticeData;
  blockId?: string;
}

defineProps<Props>();

const variantClasses: Record<string, string> = {
  default: 'bg-muted border-border',
  info: 'bg-blue-50 border-blue-200 text-blue-900 dark:bg-blue-950 dark:border-blue-800 dark:text-blue-100',
  success: 'bg-green-50 border-green-200 text-green-900 dark:bg-green-950 dark:border-green-800 dark:text-green-100',
  warning: 'bg-yellow-50 border-yellow-200 text-yellow-900 dark:bg-yellow-950 dark:border-yellow-800 dark:text-yellow-100',
  error: 'bg-red-50 border-red-200 text-red-900 dark:bg-red-950 dark:border-red-800 dark:text-red-100',
};
</script>
