// packages/react/src/blocks/StatGroupBlock.tsx
import type { StatGroupData, StatDelta } from '@mcp-interactive-ui/types';

export interface StatGroupBlockProps {
  data: StatGroupData;
  className?: string;
}

function deltaClass(d: StatDelta): string {
  if (d.direction === 'up') return 'text-emerald-600 dark:text-emerald-400';
  if (d.direction === 'down') return 'text-rose-600 dark:text-rose-400';
  return 'text-muted-foreground';
}

function deltaArrow(d: StatDelta): string {
  if (d.direction === 'up') return '↑';
  if (d.direction === 'down') return '↓';
  return '→';
}

export function StatGroupBlock({ data, className }: StatGroupBlockProps): JSX.Element {
  return (
    <div className={className ?? 'grid gap-3 grid-cols-2 lg:grid-cols-4'}>
      {data.items.map((item, i) => (
        <div
          key={i}
          className="rounded-lg border bg-card p-4 text-card-foreground shadow-sm"
        >
          <div className="text-sm text-muted-foreground">{item.label}</div>
          <div className="mt-1 text-2xl font-semibold tracking-tight">
            {typeof item.value === 'number' ? item.value.toLocaleString() : item.value}
          </div>
          {item.delta ? (
            <div className={`mt-1 text-xs ${deltaClass(item.delta)}`}>
              {deltaArrow(item.delta)} {item.delta.value}
              {item.delta.label ? ` ${item.delta.label}` : ''}
            </div>
          ) : null}
          {item.hint ? (
            <div className="mt-2 text-xs text-muted-foreground">{item.hint}</div>
          ) : null}
        </div>
      ))}
    </div>
  );
}

// packages/vue/src/components/blocks/StatGroupBlock.vue
<template>
  <div class="grid gap-4" :class="gridColsClass">
    <div
      v-for="stat in data.stats"
      :key="stat.label"
      class="rounded-lg border bg-card text-card-foreground shadow-sm p-6"
    >
      <p class="text-sm font-medium text-muted-foreground">{{ stat.label }}</p>
      <div class="mt-2 flex items-baseline gap-2">
        <span class="text-3xl font-bold tracking-tight">{{ stat.value }}</span>
        <span
          v-if="stat.change"
          :class="[
            'text-sm font-medium',
            stat.changeType === 'positive' ? 'text-green-600' : '',
            stat.changeType === 'negative' ? 'text-red-600' : 'text-muted-foreground'
          ]"
        >
          {{ stat.changeType === 'positive' ? '+' : stat.changeType === 'negative' ? '' : '' }}{{ stat.change }}
        </span>
      </div>
      <p v-if="stat.description" class="mt-1 text-xs text-muted-foreground">{{ stat.description }}</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { StatGroupData } from '@mcp-interactive-ui/types';

interface Props {
  data: StatGroupData;
  blockId?: string;
}

const props = defineProps<Props>();

const gridColsClass = computed(() => {
  const count = props.data.stats?.length ?? 1;
  if (count === 1) return 'grid-cols-1';
  if (count === 2) return 'grid-cols-1 md:grid-cols-2';
  if (count === 3) return 'grid-cols-1 md:grid-cols-3';
  if (count === 4) return 'grid-cols-2 md:grid-cols-4';
  return 'grid-cols-2 md:grid-cols-3 lg:grid-cols-4';
});
</script>
